"$schema" = 'https://starship.rs/config-schema.json'


format = """
[┌](#757575) $username$directory$git_branch$git_status$fill$cmd_duration$shell$c$dotnet$java$kotlin$nodejs$python$cmake$docker_context$package
[└](#757575) $character"""


[c]
format = " [|](#757575) [$symbol($version(-$name))]($style)"
style = "#659bd3"
symbol = "[C](#659bd3 bold) "

[cmake]
format = " [|](#757575) [$symbol($version )]($style)"
symbol = "喝"

[cmd_duration]
min_time = 0
show_milliseconds = true
format = "[$duration]($style) [|](#757575) "

[docker_context]
format = " [|](#757575) [$symbol$context]($style)"
symbol = ""
style = "bold #029ac4"

[dotnet]
format = " [|](#757575) [$symbol($version )($tfm)]($style)"
symbol = " "
style = "bold #512bd4"

[git_branch]
format = "[on](#757575) [$symbol$branch]($style)"
style = "#ff94df"

[git_status]
format = "[$untracked$modified$deleted$ahead_behind]($style)"
untracked = " $count?"
modified = " $count!"
deleted = " $count✘"
style = "#ff94df"

[java]
format = " [|](#757575) [$symbol($version)]($style)"
style = "#4f84a3"
symbol = " "

[kotlin]
format = " [|](#757575) [$symbol($version)]($style)"
style = "#7f52ff"
symbol = " "

[nodejs]
format = " [|](#757575) [$symbol($version)]($style)"
style = "green"

[package]
format = " [|](#757575) [$symbol($version)]($style)"
symbol = " "
display_private = true
style = "208"

[python]
format = " [|](#757575) [${symbol}${pyenv_prefix}(${version} )(\\($virtualenv\\) )]($style)"
symbol = " "
style = "#3871a0"

[rust]
format = " [|](#757575) $symbol($version)]($style)"
symbol = " "

[username]
style_user = "#45f1c2"
style_root = "black_red bold"
format = "[@$user]($style)"
show_always = true

[directory]
style = "#15c2cb"
format = " [in](#757575) [$path]($style) [$read_only]($read_only_style)"
read_only = ""
read_only_style = "#df5050"

[shell]
format = "[$indicator]($style)"
disabled = false

[fill]
symbol = " "

[character]
format = "$symbol "
success_symbol = "[\\$](#ffffff)"
error_symbol = "[\\$](#df5000)"

[aws]
disabled = true

[battery]
disabled = true

[buf]
disabled = true

[bun]
disabled = true

[cobol]
disabled = true

[conda]
disabled = true

[container]
disabled = true

[crystal]
disabled = true

[daml]
disabled = true

[dart]
disabled = true

[deno]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[gcloud]
disabled = true

[git_commit]
disabled = true

[git_state]
disabled = true

[golang]
disabled = true

[haskell]
disabled = true

[helm]
disabled = true

[hostname]
disabled = true

[jobs]
disabled = true

[julia]
disabled = true

[lua]
disabled = true

[meson]
disabled = true

[nim]
disabled = true

[nix_shell]
disabled = true

[ocaml]
disabled = true

[openstack]
disabled = true

[perl]
disabled = true

[php]
disabled = true

[pulumi]
disabled = true

[purescript]
disabled = true

[rlang]
disabled = true

[raku]
disabled = true

[red]
disabled = true

[ruby]
disabled = true

[scala]
disabled = true

[singularity]
disabled = true

[spack]
disabled = true

[swift]
disabled = true

[vagrant]
disabled = true

[vlang]
disabled = true

[vcsh]
disabled = true

[zig]
disabled = true